[package]
name = "predict_docs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
log = "0.4.22"
log4rs = "1.3.0"
clap = "4.5.9"
lazy_static = "1.5.0"
anyhow = "1"
csv = "1"
tokio = { version = "1.35", features = ["sync", "rt-multi-thread", "macros"] }
torch-sys =  "0.14.0"
tempfile = "3"

[lib]
name = "bert"
path = "src/lib.rs"

[features]
predict = []
pretrain = []


[[bin]]
name = "predict"
path = "src/predict.rs"
required-features = ["predict"]

[[bin]]
name = "pretrain"
path = "src/bin/pretrain.rs"
required-features = ["pretrain"]


