[package]
name = "predict_docs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
log = "0.4.22"
log4rs = "1.3.0"
clap = "4.5.9"
lazy_static = "1.5.0"
futures = "0.3.30"
anyhow = "1"
tokio = { version = "1.38.0", features = ["sync", "rt-multi-thread", "macros", "io-util", "fs"] }
tokio-stream = { version = "0.1.15", features = ["io-util"] }
tokio-metrics = "0.3.1"
tokio-console = "0.1.11"
async-stream = "0.3.5"
futures-util = "0.3.30"
csv = "1.3.0"
csv-async = "1.3.0"
serde = "1.0.204"
num_cpus = "1.16.0"
tempfile = "3"
torch-sys =  "0.14.0"
tch = "0.14.0"

[lib]
name = "bert"
path = "src/lib.rs"

[features]
predict = []
pretrain = []


[[bin]]
name = "predict"
path = "src/predict.rs"
required-features = ["predict"]

[[bin]]
name = "pretrain"
path = "src/bin/pretrain.rs"
required-features = ["pretrain"]


