refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  logfiles:
    kind: file
    path: "log/predict_docs.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - logfiles
loggers:
  bert::pretrain:
    level: debug